api/urls.py
from django.urls import path
from rest_framework_jwt.views import obtain_jwt_token

from .views import (ItemAPIList,
                    ItemAPICreate,
                    current_user,
                    UserListView,
                    ItemAPIDelete,
                    ItemCompletedAPIUpdate,)

app_name = 'api'

urlpatterns = [
    path('items/', ItemAPIList.as_view(), name='list'),
    path('items/new', ItemAPICreate.as_view(), name='create'),
    path('items/delete/<int:pk>/', ItemAPIDelete.as_view(), name='delete'),
    path('items/update/<int:pk>/', ItemCompletedAPIUpdate.as_view(), name='update'),
    path('token/', obtain_jwt_token),
    path('current-user/', current_user),
    path('users/', UserListView.as_view())

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('items.urls', namespace='items')),
    path('api/', include('api.urls', namespace='api')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

items/urls.py
from django.urls import path

from .views import ItemListViewReact

app_name = 'items'
urlpatterns = [
    path('',
         view=ItemListViewReact.as_view(),
         name='list_react'),
]

items/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify


class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)
    slug = models.SlugField(max_length=255)

    class Meta:
        ordering = ['-pub_date']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

api/views.py
from rest_framework.status import HTTP_201_CREATED, HTTP_400_BAD_REQUEST
from rest_framework.generics import ListAPIView, CreateAPIView, GenericAPIView, UpdateAPIView
from rest_framework.permissions import IsAuthenticated, AllowAny
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.mixins import DestroyModelMixin, UpdateModelMixin

from items.models import Item

from .serializers import ItemSerializer, UserSerializer, UserSerializerWithToken
from .pagination import StandardResultsPagination


@api_view(['GET'])
def current_user(request):
    serializer = UserSerializer(request.user)
    return Response(serializer.data)


class UserListView(APIView):
    permission_classes = (AllowAny,)

    def post(self, request, format=None):
        serializer = UserSerializerWithToken(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=HTTP_201_CREATED)
        return Response(serializer.errors, status=HTTP_400_BAD_REQUEST)


class ItemAPIList(ListAPIView):
    serializer_class = ItemSerializer
    pagination_class = StandardResultsPagination
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        items = Item.objects.filter(user=self.request.user, completed=False)
        return items


class ItemAPICreate(CreateAPIView):
    serializer_class = ItemSerializer
    permission_classes = (IsAuthenticated,)


class ItemAPIDelete(DestroyModelMixin, GenericAPIView):
    serializer_class = ItemSerializer
    permission_classes = (IsAuthenticated,)
    queryset = Item.objects.all()

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class ItemCompletedAPIUpdate(UpdateAPIView):
    serializer_class = ItemSerializer
    permission_classes = (IsAuthenticated,)
    queryset = Item.objects.all()

    def update(self, request, *args, **kwargs):
        instance = self.get_object()
        instance.completed = request.data.get("completed")
        instance.save()

        return Response(instance)

items/views.py
from django.views.generic import TemplateView


class ItemListViewReact(TemplateView):
    template_name = 'items/reactjs.html'

items/templates/items/item_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <div class="overlay">
        <div class="modal">
            <form method="post">{% csrf_token %}
                <p>Are you sure you want to delete "{{ object }}"?</p>
                <input type="submit" value="Confirm" />
            </form>
        </div>
    </div>
{% endblock content %}

items/templates/items/item_form.html
{% block content %}
    <form class="Item-form" action="." method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enviar">
        <a name='cancel' id='cancel' href="">Cancel</a>
    </form>
{% endblock content %}

items/templates/items/item_list.html
{% extends "base.html" %}

{% block content %}
    
<div class="Items">
    <form class='Item-form' action="{% url "api:create" %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>
    {% for item in items %}
        <div class="Item">
            <h1 class="Item-name">{{ item.name }}</h1>
            <p class="Item-description">{{ item.description }}</p>
        </div>
    {% endfor %}
</div>
{% endblock content %}

items/templates/items/reactjs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ToDO</title>
    <link href="https://fonts.googleapis.com/css?family=Sunflower:300" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "dist/css/home.css" %}">
</head>
<body>
    <div class="container" id="app">

    </div>

    <script src="{% static "dist/js/home.js" %}"></script>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ToDO</title>
    <link href="https://fonts.googleapis.com/css?family=Sunflower:300" rel="stylesheet"> 
    <link rel="stylesheet" href="{% static "css/base.css" %}">
</head>
<body>
    <div class="container">
    {% block content %}
        
    {% endblock content %}
    </div>
</body>
</html>